# Generated by Django 5.2.1 on 2025-05-22 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='careers',
            name='author_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
